// web/src/App.svelte
<script lang="ts">
  // Keyboard-first dashboard page that mirrors the TUI interaction model.

  import { onDestroy, onMount } from 'svelte';
  import { SvelteMap, SvelteSet } from 'svelte/reactivity';

  import HeaderBar from '$lib/components/HeaderBar.svelte';
  import HelpModal from '$lib/components/HelpModal.svelte';
  import GroupModal from '$lib/components/GroupModal.svelte';
  import SeriesModal from '$lib/components/SeriesModal.svelte';
  import TimingTable from '$lib/components/TimingTable.svelte';
  import NlsLivetickerModal from '$lib/components/NlsLivetickerModal.svelte';
  import MessagesModal from '$lib/components/MessagesModal.svelte';
  import { fetchSessionState, loginWithAccessCode, logoutSession, updateDemoState, fetchNlsLiveticker } from '$lib/api';
  import {
    appState,
    destroyStreams,
    favouriteKey,
    initializeAppState,
    persistPreferences,
    switchSeriesStream,
    resolveSelectedRow,
    refreshNlsLiveticker
  } from '$lib/stores/app';
  import { ALL_SERIES, type Series, type TimingEntry, type ViewMode } from '$lib/types';

  let loading = true;
  let loadError = '';
  let authenticated = false;
  let authChecking = true;
  let loginCode = '';
  let loginError = '';

  let cleanupKeys = () => {};

  onMount(async () => {
    try {
      authenticated = await fetchSessionState();
      authChecking = false;

      if (authenticated) {
        await initializeAppState();
        loading = false;
      } else {
        loading = false;
      }
    } catch (error) {
      authChecking = false;
      loading = false;
      loadError = error instanceof Error ? error.message : 'initialization failed';
      return;
    }

    const handler = (event: KeyboardEvent) => {
      if (!authenticated) {
        return;
      }

      if ($appState.search.inputActive) {
        if (event.key === 'Escape') {
          appState.update((state) => ({ ...state, search: { ...state.search, inputActive: false } }));
          event.preventDefault();
          return;
        }
        if (event.key === 'Enter') {
          appState.update((state) => ({
            ...state,
            search: { ...state.search, inputActive: false, currentMatch: 0 }
          }));
          if (searchMatches.length > 0) {
            appState.update((state) => ({ ...state, selectedRow: searchMatches[0] }));
          }
          event.preventDefault();
          return;
        }
        if (event.key === 'Backspace') {
          appState.update((state) => ({
            ...state,
            search: { ...state.search, query: state.search.query.slice(0, -1) }
          }));
          event.preventDefault();
          return;
        }
        if (event.key.length === 1 && !event.ctrlKey && !event.metaKey) {
          appState.update((state) => ({
            ...state,
            search: { ...state.search, query: `${state.search.query}${event.key}` }
          }));
          event.preventDefault();
          return;
        }
      }

      if ($appState.showSeriesPicker) {
        if (event.key === 'Escape') {
          appState.update((state) => ({ ...state, showSeriesPicker: false }));
          event.preventDefault();
          return;
        }
        if (event.key === 'ArrowDown' || event.key === 'j') {
          appState.update((state) => ({
            ...state,
            seriesPickerIndex: (state.seriesPickerIndex + 1) % ALL_SERIES.length
          }));
          event.preventDefault();
          return;
        }
        if (event.key === 'ArrowUp' || event.key === 'k') {
          appState.update((state) => ({
            ...state,
            seriesPickerIndex:
              state.seriesPickerIndex === 0 ? ALL_SERIES.length - 1 : state.seriesPickerIndex - 1
          }));
          event.preventDefault();
          return;
        }
        if (event.key === 'Enter') {
          void chooseSeries(ALL_SERIES[$appState.seriesPickerIndex]);
          event.preventDefault();
          return;
        }
      }

      if ($appState.showGroupPicker) {
        if (event.key === 'Escape') {
          appState.update((state) => ({ ...state, showGroupPicker: false }));
          event.preventDefault();
          return;
        }
        if (event.key === 'ArrowDown' || event.key === 'j') {
          appState.update((state) => ({
            ...state,
            groupPickerIndex: groups.length === 0 ? 0 : (state.groupPickerIndex + 1) % groups.length
          }));
          event.preventDefault();
          return;
        }
        if (event.key === 'ArrowUp' || event.key === 'k') {
          appState.update((state) => ({
            ...state,
            groupPickerIndex:
              groups.length === 0
                ? 0
                : state.groupPickerIndex === 0
                  ? groups.length - 1
                  : state.groupPickerIndex - 1
          }));
          event.preventDefault();
          return;
        }
        if (event.key === 'Enter') {
          pickGroup($appState.groupPickerIndex);
          event.preventDefault();
          return;
        }
      }

      // Handle modal-specific keys first
      if ($appState.showNlsLiveticker || $appState.showMessages) {
        if (event.key === 'Escape') {
          appState.update((state) => ({
            ...state,
            showNlsLiveticker: false,
            showMessages: false
          }));
          event.preventDefault();
          return;
        }
        // Let other keys pass through for scrolling within modals
        if (event.key !== 'h' && event.key !== '?' && event.key !== 'l' && event.key !== 'm') {
          // Modal will handle its own keys
          return;
        }
      }

      switch (event.key) {
        case 'Escape':
          if ($appState.showHelp) {
            appState.update((state) => ({ ...state, showHelp: false }));
          }
          break;
        case 'h':
        case '?':
          appState.update((state) => ({ ...state, showHelp: !state.showHelp }));
          break;
        case 'g':
          cycleView();
          break;
        case 'G':
          appState.update((state) => ({
            ...state,
            showGroupPicker: true,
            groupPickerIndex:
              state.viewMode.kind === 'class'
                ? groups.length === 0
                  ? 0
                  : Math.min(state.viewMode.index, groups.length - 1)
                : 0
          }));
          break;
        case 'o':
          appState.update((state) => ({ ...state, viewMode: { kind: 'overall' }, selectedRow: 0, gapAnchorStableId: null }));
          break;
        case 't':
          appState.update((state) => ({
            ...state,
            showSeriesPicker: true,
            showGroupPicker: false,
            seriesPickerIndex: ALL_SERIES.indexOf(state.activeSeries)
          }));
          break;
        case 'ArrowDown':
        case 'j':
          shiftSelection(1);
          break;
        case 'ArrowUp':
        case 'k':
          shiftSelection(-1);
          break;
        case 'PageDown':
          shiftSelection(10);
          break;
        case 'PageUp':
          shiftSelection(-10);
          break;
        case 'Home':
          appState.update((state) => ({ ...state, selectedRow: 0 }));
          break;
        case 'End':
          appState.update((state) => ({ ...state, selectedRow: Math.max(viewEntries.length - 1, 0) }));
          break;
        case ' ':
          void toggleFavourite();
          break;
        case 'f':
          jumpFavourite();
          break;
        case 's':
          appState.update((state) => ({
            ...state,
            search: { query: '', matches: [], currentMatch: 0, inputActive: true }
          }));
          break;
        case 'n':
          jumpSearch(1);
          break;
        case 'p':
          jumpSearch(-1);
          break;
        case 'd':
          void toggleDemoMode();
          break;
        case 'l':
          appState.update((state) => ({
            ...state,
            showNlsLiveticker: !state.showNlsLiveticker,
            showHelp: false,
            showMessages: false
          }));
          if (!$appState.showNlsLiveticker) {
            void refreshNlsLiveticker();
          }
          break;
        case 'm':
          appState.update((state) => ({
            ...state,
            showMessages: !state.showMessages,
            showHelp: false,
            showNlsLiveticker: false
          }));
          break;
        default:
          return;
      }
      event.preventDefault();
    };

    window.addEventListener('keydown', handler);
    cleanupKeys = () => window.removeEventListener('keydown', handler);
  });

  onDestroy(() => {
    cleanupKeys();
    destroyStreams();
  });

  async function submitLogin(): Promise<void> {
    loginError = '';
    const result = await loginWithAccessCode(loginCode.trim());
    if (!result.ok) {
      loginError =
        result.retryAfterSecs && result.retryAfterSecs > 0
          ? `${result.error ?? 'login blocked'} (retry in ${result.retryAfterSecs}s)`
          : (result.error ?? 'Invalid access code');
      return;
    }

    authenticated = true;
    loginCode = '';
    await initializeAppState();
  }

  async function signOut(): Promise<void> {
    await logoutSession();
    destroyStreams();
    authenticated = false;
    appState.update((state) => ({
      ...state,
      snapshots: {},
      selectedRow: 0,
      gapAnchorStableId: null,
      showHelp: false,
      showSeriesPicker: false,
      showGroupPicker: false,
      search: { query: '', matches: [], currentMatch: 0, inputActive: false }
    }));
  }

  function normalizeClassName(value: string): string {
    return value.replaceAll(' ', '').replaceAll('_', '').toUpperCase();
  }

  function classDisplayName(value: string): string {
    const normalized = normalizeClassName(value);
    if (normalized === 'GTDPRO') {
      return 'GTD PRO';
    }
    return value.trim() || '-';
  }

  function groupedEntries(entries: TimingEntry[]): [string, TimingEntry[]][] {
    const grouped = new SvelteMap<string, TimingEntry[]>();
    for (const entry of entries) {
      const group = classDisplayName(entry.class_name);
      if (!grouped.has(group)) {
        grouped.set(group, []);
      }
      grouped.get(group)?.push(entry);
    }

    const groups = Array.from(grouped.entries());

    for (const group of groups) {
      group[1].sort((a, b) => Number(a.class_rank || 9999) - Number(b.class_rank || 9999));
    }

    // Match TUI behavior: order groups by best overall position in class.
    groups.sort((a, b) => {
      const aBest = a[1].reduce((min, entry) => Math.min(min, entry.position), Number.MAX_SAFE_INTEGER);
      const bBest = b[1].reduce((min, entry) => Math.min(min, entry.position), Number.MAX_SAFE_INTEGER);
      if (aBest !== bBest) return aBest - bBest;
      return a[0].localeCompare(b[0]);
    });

    return groups;
  }

  function nextViewMode(current: ViewMode, groupCount: number): ViewMode {
    if (groupCount === 0) {
      if (current.kind === 'overall') return { kind: 'grouped' };
      if (current.kind === 'grouped') return { kind: 'favourites' };
      return { kind: 'overall' };
    }

    if (current.kind === 'overall') return { kind: 'grouped' };
    if (current.kind === 'grouped') return { kind: 'class', index: 0 };
    if (current.kind === 'class') {
      return current.index + 1 < groupCount
        ? { kind: 'class', index: current.index + 1 }
        : { kind: 'favourites' };
    }
    return { kind: 'overall' };
  }

  function cycleView(): void {
    appState.update((state) => {
      const groups = groupedEntries(activeEntries);
      return {
        ...state,
        viewMode: nextViewMode(state.viewMode, groups.length),
        selectedRow: 0,
        gapAnchorStableId: null
      };
    });
  }

  function shiftSelection(delta: number): void {
    appState.update((state) => {
      const max = Math.max(viewEntries.length - 1, 0);
      const next = Math.max(0, Math.min(max, state.selectedRow + delta));
      return { ...state, selectedRow: next };
    });
  }

  async function toggleFavourite(): Promise<void> {
    const selected = viewEntries[$appState.selectedRow];
    if (!selected) return;
    const key = favouriteKey($appState.activeSeries, selected.stable_id);
    appState.update((state) => {
      const next = new SvelteSet(state.favourites);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return { ...state, favourites: next };
    });
    await persistPreferences();
  }

  function jumpFavourite(): void {
    if (viewEntries.length === 0) return;
    const start = $appState.selectedRow;
    for (let offset = 1; offset <= viewEntries.length; offset += 1) {
      const idx = (start + offset) % viewEntries.length;
      const key = favouriteKey($appState.activeSeries, viewEntries[idx].stable_id);
      if ($appState.favourites.has(key)) {
        appState.update((state) => ({
          ...state,
          selectedRow: idx,
          gapAnchorStableId: viewEntries[idx].stable_id
        }));
        return;
      }
    }
  }

  function entryMatchesSearch(entry: TimingEntry, query: string): boolean {
    const needle = query.trim().toLowerCase();
    if (!needle) return false;
    return (
      entry.car_number.toLowerCase().includes(needle) ||
      entry.driver.toLowerCase().includes(needle) ||
      entry.vehicle.toLowerCase().includes(needle) ||
      entry.team.toLowerCase().includes(needle)
    );
  }

  function jumpSearch(delta: number): void {
    if (searchMatches.length === 0) return;
    appState.update((state) => {
      const start = Math.min(state.search.currentMatch, searchMatches.length - 1);
      const next = (start + delta + searchMatches.length) % searchMatches.length;
      return {
        ...state,
        selectedRow: searchMatches[next],
        search: { ...state.search, currentMatch: next }
      };
    });
  }

  async function chooseSeries(series: Series): Promise<void> {
    appState.update((state) => ({
      ...state,
      activeSeries: series,
      showSeriesPicker: false,
      showGroupPicker: false,
      seriesPickerIndex: ALL_SERIES.indexOf(series),
      viewMode: { kind: 'overall' },
      selectedRow: 0,
      gapAnchorStableId: null
    }));
    switchSeriesStream(series);
    await persistPreferences();
  }

  async function toggleDemoMode(): Promise<void> {
    const nextEnabled = !$appState.demoEnabled;
    const result = await updateDemoState(nextEnabled);
    appState.update((state) => ({ ...state, demoEnabled: result.enabled }));
    destroyStreams();
    await initializeAppState();
  }

  function pickGroup(index: number): void {
    if (groups.length === 0) {
      appState.update((state) => ({ ...state, showGroupPicker: false }));
      return;
    }
    const bounded = Math.max(0, Math.min(index, groups.length - 1));
    appState.update((state) => ({
      ...state,
      viewMode: { kind: 'class', index: bounded },
      selectedRow: 0,
      gapAnchorStableId: null,
      showGroupPicker: false,
      groupPickerIndex: bounded
    }));
  }

  $: activeSnapshot = $appState.snapshots[$appState.activeSeries] ?? null;
  $: activeEntries = activeSnapshot?.entries ?? [];
  $: groups = groupedEntries(activeEntries);
  $: groupedSections = (() => {
    let start = 0;
    return groups.map(([name, entries]) => {
      const section = { name, entries, start };
      start += entries.length;
      return section;
    });
  })();
  $: favouriteEntries = activeEntries.filter((entry) =>
    $appState.favourites.has(favouriteKey($appState.activeSeries, entry.stable_id))
  );
  $: viewEntries = (() => {
    const mode = $appState.viewMode;
    if (mode.kind === 'overall') return activeEntries;
    if (mode.kind === 'grouped') return groups.flatMap(([, entries]) => entries);
    if (mode.kind === 'class') return groups[mode.index]?.[1] ?? [];
    return favouriteEntries;
  })();
  $: if (
    $appState.gapAnchorStableId &&
    !viewEntries.some((entry) => entry.stable_id === $appState.gapAnchorStableId)
  ) {
    appState.update((state) => ({ ...state, gapAnchorStableId: null }));
  }
  $: searchMatches = viewEntries
    .map((entry, index) => (entryMatchesSearch(entry, $appState.search.query) ? index : -1))
    .filter((idx) => idx >= 0);
  $: searchCurrentMatch =
    searchMatches.length === 0
      ? 0
      : Math.min($appState.search.currentMatch, searchMatches.length - 1);
  $: markedStableId =
    searchMatches.length === 0 ? null : (viewEntries[searchMatches[searchCurrentMatch]]?.stable_id ?? null);
  $: viewModeLabel =
    $appState.viewMode.kind === 'class'
      ? `Class ${groups[$appState.viewMode.index]?.[0] ?? ''}`
      : $appState.viewMode.kind[0].toUpperCase() + $appState.viewMode.kind.slice(1);
  $: searchLabel = $appState.search.query
    ? `Search: ${$appState.search.query}${$appState.search.inputActive ? '_' : ''} (${searchMatches.length === 0 ? 0 : searchCurrentMatch + 1}/${searchMatches.length})`
    : '';
  $: effectiveFlag = (activeSnapshot?.header.flag && activeSnapshot.header.flag.trim()) || '-';
  $: demoLabel = $appState.demoEnabled ? '| DEMO' : '';
  $: favCountForSeries = Array.from($appState.favourites).filter((value) =>
    value.startsWith(`${$appState.activeSeries}|`)
  ).length;
</script>

<main>
  {#if authChecking}
    <p>Checking access...</p>
  {:else if !authenticated}
    <section class="login-wrap">
      <div class="login-card">
        <h1>Live Timing Access</h1>
        <p>Enter the shared access code to open the timing dashboard.</p>
        <form
          on:submit|preventDefault={() => {
            void submitLogin();
          }}
        >
          <input
            placeholder="Access code"
            bind:value={loginCode}
            type="password"
            autocomplete="current-password"
          />
          <button type="submit">Enter</button>
        </form>
        {#if loginError}
          <p class="login-error">{loginError}</p>
        {/if}
      </div>
    </section>
  {:else if loading}
    <p>Loading web UI...</p>
  {:else if loadError}
    <p>Failed to initialize: {loadError}</p>
  {:else}
    <div class="header-row">
      <HeaderBar
        series={$appState.activeSeries}
        snapshot={activeSnapshot}
        viewModeLabel={viewModeLabel}
        favCount={favCountForSeries}
        searchLabel={searchLabel}
        demoLabel={demoLabel}
        errorText={activeSnapshot?.last_error ?? ''}
        displayFlag={effectiveFlag}
        searchQuery={$appState.search.query}
        searchMatches={searchMatches.length}
        searchCurrentMatch={searchCurrentMatch}
        searchInputActive={$appState.search.inputActive}
      />
      <button class="logout-btn" on:click={() => void signOut()}>Logout</button>
    </div>

    <TimingTable
      title={viewModeLabel}
      series={$appState.activeSeries}
      entries={viewEntries}
      classColors={activeSnapshot?.header.class_colors as Record<string, import('$lib/types').TimingClassColor> ?? {}}
      groupedSections={groupedSections}
      isGroupedMode={$appState.viewMode.kind === 'grouped'}
      selectedRow={$appState.selectedRow}
      markedStableId={markedStableId}
      favourites={$appState.favourites}
      gapAnchorStableId={$appState.gapAnchorStableId}
    />

    <HelpModal open={$appState.showHelp} />
    <GroupModal
      open={$appState.showGroupPicker}
      groups={groups.map(([name]) => name)}
      selectedIndex={$appState.groupPickerIndex}
      onPick={pickGroup}
    />
    <SeriesModal
      open={$appState.showSeriesPicker}
      selectedSeries={ALL_SERIES[$appState.seriesPickerIndex]}
      onPick={chooseSeries}
    />
    <NlsLivetickerModal
      open={$appState.showNlsLiveticker}
      entries={$appState.nlsLiveticker.entries}
      lastUpdateUnixMs={$appState.nlsLiveticker.lastUpdateUnixMs}
      lastError={$appState.nlsLiveticker.lastError}
    />
    <MessagesModal
      open={$appState.showMessages}
      notices={activeSnapshot?.notices ?? []}
    />
  {/if}
</main>

<style>
  main {
    max-width: 100%;
    height: 100dvh;
    min-height: 100dvh;
    padding: 0.7rem;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  p {
    color: var(--text-dim);
  }

  .login-wrap {
    flex: 1;
    display: grid;
    place-items: center;
  }

  .login-card {
    width: min(28rem, 92vw);
    border: 1px solid var(--border);
    border-radius: 8px;
    background: #0d1b2c;
    padding: 1rem;
  }

  .login-card h1 {
    margin: 0 0 0.45rem;
    font-size: 1.1rem;
  }

  .login-card p {
    margin: 0 0 0.75rem;
  }

  .login-card form {
    display: flex;
    gap: 0.45rem;
  }

  .login-card input,
  .login-card button,
  .logout-btn {
    font-family: inherit;
    background: #13263a;
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text);
    padding: 0.45rem 0.6rem;
  }

  .login-card input {
    flex: 1;
  }

  .login-error {
    color: #ff8a8a;
    margin-top: 0.55rem;
  }

  .header-row {
    display: flex;
    align-items: stretch;
    gap: 0.45rem;
    margin-bottom: 0.35rem;
  }

  .header-row :global(.header) {
    flex: 1;
  }

  .logout-btn {
    white-space: nowrap;
    align-self: stretch;
    height: auto;
    display: flex;
    align-items: center;
  }

  @media (max-width: 768px) {
    .header-row {
      flex-direction: column;
    }

    .logout-btn {
      align-self: flex-start;
    }
  }

  @media (max-width: 768px) {
    main {
      height: 100dvh;
      padding: 0.4rem;
    }
  }
</style>

// web/src/app.tsx
// Main App component
import { useCallback, useEffect, useMemo, useState, type JSX } from 'react';

import {
  fetchSessionState,
  loginWithAccessCode,
  updateDemoState,
} from './lib/api';
import { HeaderBar } from './lib/components/header-bar';
import { HelpModal } from './lib/components/help-modal';
import { MessagesModal } from './lib/components/messages-modal';
import { NlsLivetickerModal } from './lib/components/nls-liveticker-modal';
import { SeriesModal } from './lib/components/series-modal';
import { TimingTable } from './lib/components/timing-table';
import { useAppState, useKeyboard, type AppState, type UseAppStateReturn } from './lib/hooks';
import { ALL_SERIES, type Series, type TimingEntry, type ViewMode } from './lib/types';

import './app.css';

const SLICE_START_INDEX = 0;
const DEFAULT_GROUP_PICKER_INDEX = 0;
const DEFAULT_SELECTED_ROW = 0;
const FIRST_MATCH_INDEX = 0;
const INDEX_DECREMENT = -1;
const INDEX_INCREMENT = 1;
const JUMP_BACKWARD = -1;
const JUMP_FORWARD = 1;
const KEY_LENGTH_SINGLE = 1;
const MINIMUM_GROUP_COUNT = 0;
const MINIMUM_LENGTH = 0;
const PAGE_JUMP_SIZE = 10;
const SLICE_REMOVE_LAST = 1;
const ZERO_LENGTH = 0;

// Helper functions (hoisted before App component for no-use-before-define rule)
const classDisplayName = (value: string): string => {
  const normalized: string = value.replaceAll(' ', '').replaceAll('_', '').toUpperCase();
  if (normalized === 'GTDPRO') {
    return 'GTD PRO';
  }
  return value.trim() || '-';
};

const getGroups = (entries: TimingEntry[]): string[] => {
  const grouped = new Map<string, TimingEntry[]>();
  for (const entry of entries) {
    const group: string = classDisplayName(entry.class_name);
    if (!grouped.has(group)) {
      grouped.set(group, []);
    }
    const groupEntries: TimingEntry[] | undefined = grouped.get(group);
    if (groupEntries !== undefined) {
      groupEntries.push(entry);
    }
  }
  return [...grouped.keys()].sort();
};

const nextViewMode = (current: ViewMode, groupCount: number): ViewMode => {
  if (groupCount === MINIMUM_GROUP_COUNT) {
    if (current.kind === 'overall') {
      return { kind: 'grouped' };
    }
    if (current.kind === 'grouped') {
      return { kind: 'favourites' };
    }
    return { kind: 'overall' };
  }
  if (current.kind === 'overall') {
    return { kind: 'grouped' };
  }
  if (current.kind === 'grouped') {
    return { index: 0, kind: 'class' };
  }
  if (current.kind === 'class') {
    return current.index + INDEX_INCREMENT < groupCount
      ? { index: current.index + INDEX_INCREMENT, kind: 'class' }
      : { kind: 'favourites' };
  }
  return { kind: 'overall' };
};

export const App = (): JSX.Element => {
  const {
    activeSnapshot,
    destroyStreams,
    favouriteKey,
    initializeAppState,
    persistPreferences,
    refreshNlsLiveticker,
    setState,
    state,
    switchSeriesStream,
  }: UseAppStateReturn = useAppState();

  const [authChecking, setAuthChecking] = useState<boolean>(true);
  const [authenticated, setAuthenticated] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(true);
  const [loadError, setLoadError] = useState<string>('');
  const [loginCode, setLoginCode] = useState<string>('');
  const [loginError, setLoginError] = useState<string>('');

  // Derived values
  const activeEntries: TimingEntry[] = useMemo((): TimingEntry[] => {
    const entries: TimingEntry[] = activeSnapshot?.entries ?? [];
    if (state.viewMode.kind === 'favourites') {
      return entries.filter((entry: TimingEntry): boolean => {
        const key: string = favouriteKey(state.activeSeries, entry.stable_id);
        return state.favourites.has(key);
      });
    }
    if (state.viewMode.kind === 'class' && state.groups.length > MINIMUM_LENGTH) {
      const group: string = state.groups[state.viewMode.index];
      return entries.filter((entry: TimingEntry): boolean => classDisplayName(entry.class_name) === group);
    }
    return entries;
  }, [
    activeSnapshot?.entries,
    favouriteKey,
    state.activeSeries,
    state.favourites,
    state.groups,
    state.viewMode,
  ]);

  const searchMatches: number[] = useMemo((): number[] => {
    if (state.search.query === '') {
      return [];
    }
    const matches: number[] = [];
    const query: string = state.search.query.toLowerCase();
    for (let index = FIRST_MATCH_INDEX; index < activeEntries.length; index += INDEX_INCREMENT) {
      const entry: TimingEntry = activeEntries[index];
      if (
        entry.car_number.toLowerCase().includes(query) ||
        entry.driver.toLowerCase().includes(query) ||
        entry.vehicle.toLowerCase().includes(query) ||
        entry.team.toLowerCase().includes(query)
      ) {
        matches.push(index);
      }
    }
    return matches;
  }, [activeEntries, state.search.query]);

  // Actions
  const chooseSeries = useCallback(async (series: Series): Promise<void> => {
    setState((prev: AppState) => ({
      ...prev,
      activeSeries: series,
      gapAnchorStableId: null,
      selectedRow: DEFAULT_SELECTED_ROW,
      showGroupPicker: false,
      showSeriesPicker: false,
      viewMode: { kind: 'overall' },
    }));
    switchSeriesStream(series);
    await persistPreferences();
  }, [persistPreferences, setState, switchSeriesStream]);

  const cycleView = useCallback((): void => {
    const groups = getGroups(activeSnapshot?.entries ?? []);
    setState((prev: AppState) => ({
      ...prev,
      gapAnchorStableId: null,
      selectedRow: DEFAULT_SELECTED_ROW,
      viewMode: nextViewMode(prev.viewMode, groups.length),
    }));
  }, [activeSnapshot?.entries, setState]);

  const jumpFavourite = useCallback((): void => {
    if (activeEntries.length === MINIMUM_LENGTH) {
      return;
    }
    const start: number = state.selectedRow;
    for (let offset = INDEX_INCREMENT; offset <= activeEntries.length; offset += INDEX_INCREMENT) {
      const idx: number = (start + offset) % activeEntries.length;
      const entry: TimingEntry = activeEntries[idx];
      const key: string = favouriteKey(state.activeSeries, entry.stable_id);
      if (state.favourites.has(key)) {
        setState((prev: AppState) => ({
          ...prev,
          gapAnchorStableId: entry.stable_id,
          selectedRow: idx,
        }));
        return;
      }
    }
  }, [activeEntries, favouriteKey, setState, state.activeSeries, state.favourites, state.selectedRow]);

  const jumpSearch = useCallback((delta: number): void => {
    if (searchMatches.length === MINIMUM_LENGTH) {
      return;
    }
    setState((prev: AppState) => {
      const start = Math.min(prev.search.currentMatch, searchMatches.length + INDEX_DECREMENT);
      const next = (start + delta + searchMatches.length) % searchMatches.length;
      return {
        ...prev,
        search: { ...prev.search, currentMatch: next },
        selectedRow: searchMatches[next],
      };
    });
  }, [searchMatches, setState]);

  const selectGroup = useCallback((index: number): void => {
    setState((prev: AppState) => ({
      ...prev,
      gapAnchorStableId: null,
      groupPickerIndex: index,
      selectedRow: DEFAULT_SELECTED_ROW,
      showGroupPicker: false,
      viewMode: { index, kind: 'class' },
    }));
  }, [setState]);

  const shiftSelection = useCallback((delta: number): void => {
    setState((prev: AppState) => {
      const max = Math.max(activeEntries.length + INDEX_DECREMENT, DEFAULT_SELECTED_ROW);
      const next = Math.max(DEFAULT_SELECTED_ROW, Math.min(max, prev.selectedRow + delta));
      return { ...prev, selectedRow: next };
    });
  }, [activeEntries.length, setState]);

  const submitLogin = useCallback(async (): Promise<void> => {
    setLoginError('');
    const result = await loginWithAccessCode(loginCode.trim());
    if (!result.ok) {
      setLoginError(
        result.retryAfterSecs !== undefined && result.retryAfterSecs > ZERO_LENGTH
          ? `${result.error ?? 'login blocked'} (retry in ${String(result.retryAfterSecs)}s)`
          : (result.error ?? 'Invalid access code'),
      );
      return;
    }
    setAuthenticated(true);
    setLoginCode('');
    await initializeAppState();
  }, [initializeAppState, loginCode]);

  const toggleDemoMode = useCallback(async (): Promise<void> => {
    const nextEnabled = !state.demoEnabled;
    await updateDemoState(nextEnabled);
    setState((prev: AppState) => ({ ...prev, demoEnabled: nextEnabled }));
  }, [setState, state.demoEnabled]);

  const toggleFavourite = useCallback(async (): Promise<void> => {
    const selected: TimingEntry = activeEntries[state.selectedRow];
    const key = favouriteKey(state.activeSeries, selected.stable_id);
    setState((prev: AppState) => {
      const next = new Set(prev.favourites);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return { ...prev, favourites: next };
    });
    await persistPreferences();
  }, [activeEntries, favouriteKey, persistPreferences, setState, state.activeSeries, state.selectedRow]);

  // Keyboard handlers
  const handleGroupPickerKeydown = useCallback((event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      setState((prev: AppState) => ({ ...prev, showGroupPicker: false }));
      event.preventDefault();
    } else if (event.key === 'ArrowDown' || event.key === 'j') {
      setState((prev: AppState) => ({
        ...prev,
        groupPickerIndex: (prev.groupPickerIndex + INDEX_INCREMENT) % state.groups.length,
      }));
      event.preventDefault();
    } else if (event.key === 'ArrowUp' || event.key === 'k') {
      setState((prev: AppState) => ({
        ...prev,
        groupPickerIndex:
          prev.groupPickerIndex === DEFAULT_GROUP_PICKER_INDEX
            ? state.groups.length + INDEX_DECREMENT
            : prev.groupPickerIndex + INDEX_DECREMENT,
      }));
      event.preventDefault();
    } else if (event.key === 'Enter') {
      selectGroup(state.groupPickerIndex);
      event.preventDefault();
    }
  }, [selectGroup, setState, state.groupPickerIndex, state.groups.length]);

  const handleMainKeydown = useCallback((event: KeyboardEvent): void => {
    switch (event.key) {
      case 'Escape': {
        if (state.showHelp) {
          setState((prev: AppState) => ({ ...prev, showHelp: false }));
          event.preventDefault();
        }
        break;
      }
      case 'h':
      case '?': {
        setState((prev: AppState) => ({ ...prev, showHelp: !prev.showHelp }));
        event.preventDefault();
        break;
      }
      case 'g': {
        cycleView();
        event.preventDefault();
        break;
      }
      case 'G': {
        setState((prev: AppState) => ({
          ...prev,
          groupPickerIndex:
            prev.viewMode.kind === 'class' && prev.groups.length > MINIMUM_LENGTH
              ? Math.min(prev.viewMode.index, prev.groups.length + INDEX_DECREMENT)
              : DEFAULT_GROUP_PICKER_INDEX,
          showGroupPicker: true,
        }));
        event.preventDefault();
        break;
      }
      case 'o': {
        setState((prev: AppState) => ({
          ...prev,
          gapAnchorStableId: null,
          selectedRow: DEFAULT_SELECTED_ROW,
          viewMode: { kind: 'overall' },
        }));
        event.preventDefault();
        break;
      }
      case 't': {
        setState((prev: AppState) => ({
          ...prev,
          seriesPickerIndex: ALL_SERIES.indexOf(prev.activeSeries),
          showSeriesPicker: true,
        }));
        event.preventDefault();
        break;
      }
      case 'ArrowDown':
      case 'j': {
        shiftSelection(JUMP_FORWARD);
        event.preventDefault();
        break;
      }
      case 'ArrowUp':
      case 'k': {
        shiftSelection(JUMP_BACKWARD);
        event.preventDefault();
        break;
      }
      case 'PageDown': {
        shiftSelection(PAGE_JUMP_SIZE);
        event.preventDefault();
        break;
      }
      case 'PageUp': {
        shiftSelection(-PAGE_JUMP_SIZE);
        event.preventDefault();
        break;
      }
      case 'Home': {
        setState((prev: AppState) => ({ ...prev, selectedRow: DEFAULT_SELECTED_ROW }));
        event.preventDefault();
        break;
      }
      case 'End': {
        setState((prev: AppState) => ({
          ...prev,
          selectedRow: Math.max(activeEntries.length + INDEX_DECREMENT, DEFAULT_SELECTED_ROW),
        }));
        event.preventDefault();
        break;
      }
      case ' ': {
        void toggleFavourite();
        event.preventDefault();
        break;
      }
      case 'f': {
        jumpFavourite();
        event.preventDefault();
        break;
      }
      case 's': {
        setState((prev: AppState) => ({
          ...prev,
          search: {
            currentMatch: 0,
            inputActive: true,
            matches: [],
            query: '',
          },
        }));
        event.preventDefault();
        break;
      }
      case 'n': {
        jumpSearch(JUMP_FORWARD);
        event.preventDefault();
        break;
      }
      case 'p': {
        jumpSearch(JUMP_BACKWARD);
        event.preventDefault();
        break;
      }
      case 'd': {
        void toggleDemoMode();
        event.preventDefault();
        break;
      }
      case 'l': {
        setState((prev: AppState) => ({
          ...prev,
          showHelp: false,
          showMessages: false,
          showNlsLiveticker: !prev.showNlsLiveticker,
        }));
        if (!state.showNlsLiveticker) {
          void refreshNlsLiveticker();
        }
        event.preventDefault();
        break;
      }
      case 'm': {
        setState((prev: AppState) => ({
          ...prev,
          showHelp: false,
          showMessages: !prev.showMessages,
          showNlsLiveticker: false,
        }));
        event.preventDefault();
        break;
      }
      default: {
        break;
      }
    }
  }, [activeEntries.length, cycleView, jumpFavourite, jumpSearch, refreshNlsLiveticker, setState, shiftSelection, state.showHelp, state.showNlsLiveticker, toggleDemoMode, toggleFavourite]);

  const handleSearchKeydown = useCallback((event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      setState((prev: AppState) => ({
        ...prev,
        search: { ...prev.search, inputActive: false },
      }));
      event.preventDefault();
    } else if (event.key === 'Enter') {
      setState((prev: AppState) => ({
        ...prev,
        search: { ...prev.search, currentMatch: FIRST_MATCH_INDEX, inputActive: false },
      }));
      if (searchMatches.length > MINIMUM_LENGTH) {
        setState((prev: AppState) => ({ ...prev, selectedRow: searchMatches[FIRST_MATCH_INDEX] }));
      }
      event.preventDefault();
    } else if (event.key === 'Backspace') {
      setState((prev: AppState) => ({
        ...prev,
        search: {
          ...prev.search,
          query: prev.search.query.slice(SLICE_START_INDEX, -SLICE_REMOVE_LAST),
        },
      }));
      event.preventDefault();
    } else if (event.key.length === KEY_LENGTH_SINGLE && !event.ctrlKey && !event.metaKey) {
      setState((prev: AppState) => ({
        ...prev,
        search: {
          ...prev.search,
          query: prev.search.query + event.key,
        },
      }));
      event.preventDefault();
    }
  }, [searchMatches, setState]);

  const handleSeriesPickerKeydown = useCallback((event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      setState((prev: AppState) => ({ ...prev, showSeriesPicker: false }));
      event.preventDefault();
    } else if (event.key === 'ArrowDown' || event.key === 'j') {
      setState((prev: AppState) => ({
        ...prev,
        seriesPickerIndex: (prev.seriesPickerIndex + INDEX_INCREMENT) % ALL_SERIES.length,
      }));
      event.preventDefault();
    } else if (event.key === 'ArrowUp' || event.key === 'k') {
      setState((prev: AppState) => ({
        ...prev,
        seriesPickerIndex:
          prev.seriesPickerIndex === DEFAULT_GROUP_PICKER_INDEX
            ? ALL_SERIES.length + INDEX_DECREMENT
            : prev.seriesPickerIndex + INDEX_DECREMENT,
      }));
      event.preventDefault();
    } else if (event.key === 'Enter') {
      void chooseSeries(ALL_SERIES[state.seriesPickerIndex]);
      event.preventDefault();
    }
  }, [chooseSeries, setState, state.seriesPickerIndex]);

  // Initialize
  useEffect(() => {
    const init = async (): Promise<void> => {
      try {
        const isAuth = await fetchSessionState();
        setAuthenticated(isAuth);
        setAuthChecking(false);
        if (isAuth) {
          await initializeAppState();
        }
        setLoading(false);
      } catch (error) {
        setAuthChecking(false);
        setLoading(false);
        setLoadError(error instanceof Error ? error.message : 'initialization failed');
      }
    };
    void init();

    return (): void => {
      destroyStreams();
    };
  }, [destroyStreams, initializeAppState]);

  // Keyboard handler
  const handleKeydown = useCallback(
    (event: KeyboardEvent): void => {
      if (!authenticated) {
        return;
      }

      if (state.search.inputActive) {
        handleSearchKeydown(event);
        return;
      }

      if (state.showSeriesPicker) {
        handleSeriesPickerKeydown(event);
        return;
      }

      if (state.showGroupPicker) {
        handleGroupPickerKeydown(event);
        return;
      }

      handleMainKeydown(event);
    },
    [authenticated, handleGroupPickerKeydown, handleMainKeydown, handleSearchKeydown, handleSeriesPickerKeydown, state.search.inputActive, state.showGroupPicker, state.showSeriesPicker],
  );

  useKeyboard(handleKeydown);

  // Render helpers
  useMemo(() => getGroups(activeSnapshot?.entries ?? []), [activeSnapshot?.entries]);

  if (authChecking) {
    return <div className="loading">Checking session...</div>;
  }

  if (!authenticated) {
    return (
      <div className="login-container">
        <h1>IMSA Live Timing</h1>
        <input
          onChange={(event): void => { setLoginCode(event.target.value); }}
          placeholder="Enter access code"
          type="text"
          value={loginCode}
        />
        <button onClick={(): void => { void submitLogin(); }} type="button">
          Login
        </button>
        {loginError && <div className="error">{loginError}</div>}
      </div>
    );
  }

  if (loading) {
    return <div className="loading">Loading...</div>;
  }

  if (loadError) {
    return <div className="error">{loadError}</div>;
  }

  const favCount = useMemo(() =>
    [...state.favourites].filter((favourite) =>
      favourite.startsWith(`${state.activeSeries}|`),
    ).length,
  [state.activeSeries, state.favourites]);

  // View mode label with IIFE to avoid nested ternary and init-declarations rule
  const viewModeLabel = ((): string => {
    if (state.viewMode.kind === 'overall') {
      return 'Overall';
    }
    if (state.viewMode.kind === 'grouped') {
      return 'Grouped';
    }
    if (state.viewMode.kind === 'favourites') {
      return 'Favourites';
    }
    return `Class ${state.viewMode.index + INDEX_INCREMENT}`;
  })();

  const searchLabel = state.search.query
    ? `${state.search.query} (${state.search.currentMatch + INDEX_INCREMENT}/${searchMatches.length})`
    : '';

  const demoLabel = state.demoEnabled ? '| DEMO' : '';

  return (
    <div className="app">
      <HeaderBar
        demoLabel={demoLabel}
        errorText={state.connectionErrors[FIRST_MATCH_INDEX] ?? ''}
        favCount={favCount}
        searchCurrentMatch={state.search.currentMatch}
        searchInputActive={state.search.inputActive}
        searchLabel={searchLabel}
        searchMatches={searchMatches.length}
        searchQuery={state.search.query}
        series={state.activeSeries}
        snapshot={activeSnapshot ?? null}
        viewModeLabel={viewModeLabel}
      />

      <TimingTable
        classColors={activeSnapshot?.header.class_colors ?? {}}
        entries={activeEntries}
        selectedRow={state.selectedRow}
        series={state.activeSeries}
      />

      <HelpModal
        onClose={(): void => { setState((prev: AppState) => ({ ...prev, showHelp: false })); }}
        open={state.showHelp}
      />

      <SeriesModal
        onPick={(series): void => { void chooseSeries(series); }}
        open={state.showSeriesPicker}
        selectedIndex={state.seriesPickerIndex}
        selectedSeries={state.activeSeries}
      />

      <MessagesModal
        notices={activeSnapshot?.notices ?? []}
        onClose={(): void => { setState((prev: AppState) => ({ ...prev, showMessages: false })); }}
        open={state.showMessages}
      />

      <NlsLivetickerModal
        entries={state.nlsLiveticker.entries}
        lastError={state.nlsLiveticker.lastError}
        lastUpdateUnixMs={state.nlsLiveticker.lastUpdateUnixMs}
        onClose={(): void => { setState((prev: AppState) => ({ ...prev, showNlsLiveticker: false })); }}
        open={state.showNlsLiveticker}
      />
    </div>
  );
};
