// web/src/lib/components/header-bar.tsx
// Header-bar.tsx - Status header matching TUI metadata order and flag-driven theming
import type { JSX } from 'react';

import type { SeriesSnapshot } from '../generated/web-shared';

interface HeaderBarProps {
  demoLabel: string;
  favCount: number;
  searchCurrentMatch: number;
  searchInputActive: boolean;
  searchLabel: string;
  searchMatches: number;
  searchQuery: string;
  snapshot: SeriesSnapshot | null;
  viewModeLabel: string;
}

const MS_PER_SECOND = 1000;
const INDEX_OFFSET = 1;
const MIN_VALUE = 0;
const SLICE_OFFSET = 1;

const normalizeImsaLabel = function normalizeImsaLabel(raw: string): string {
  const trimmed = raw.trim();
  const lower = trimmed.toLowerCase();
  if (lower.includes('weathertech')) {
    const idx = Math.max(
      trimmed.lastIndexOf('-'),
      trimmed.lastIndexOf('–'),
      trimmed.lastIndexOf('—'),
    );
    if (idx >= MIN_VALUE) {
      return trimmed.slice(idx + SLICE_OFFSET).trim();
    }
  }
  return trimmed;
};

export const HeaderBar = function HeaderBar(props: HeaderBarProps): JSX.Element {
  const {
    demoLabel,
    favCount,
    searchCurrentMatch,
    searchInputActive,
    searchLabel,
    searchMatches,
    searchQuery,
    snapshot,
    viewModeLabel,
  } = props;

  const statusText = snapshot?.status ?? 'Starting live timing...';

  // Event name formatting
  const rawEventName = snapshot?.header.event_name;
  const eventText =
    rawEventName === undefined || rawEventName.trim() === '' ? '-' : rawEventName.trim();

  // Session name formatting with IMSA normalization
  const rawSessionName = snapshot?.header.session_name;
  const sessionText =
    rawSessionName === undefined || rawSessionName.trim() === ''
      ? '-'
      : normalizeImsaLabel(rawSessionName);

  const rawTimeToGo = snapshot?.header.time_to_go;
  const timeToGo = rawTimeToGo === undefined || rawTimeToGo === '' ? '-' : rawTimeToGo;
  const flag = snapshot?.header.flag ?? '';
  const displayFlag = flag.length > MIN_VALUE ? flag : '-';

  // Age calculation from last_update_unix_ms
  const rawUpdateMs = snapshot?.last_update_unix_ms;
  const ageText =
    rawUpdateMs !== undefined && rawUpdateMs !== null
      ? `Upd ${Math.max(
          MIN_VALUE,
          Math.floor((Date.now() - Number(rawUpdateMs)) / MS_PER_SECOND),
        )}s`
      : 'Upd -';

  // Error from snapshot.last_error
  const rawError = snapshot?.last_error;
  const errorText = rawError ?? '';

  // Search count display logic
  const searchCount = ((): JSX.Element | null => {
    if (searchMatches > MIN_VALUE) {
      return (
        <span className="search-count">
          ({searchCurrentMatch + INDEX_OFFSET}/{searchMatches})
        </span>
      );
    }
    if (searchQuery) {
      return <span className="search-count">(0/0)</span>;
    }
    return null;
  })();

  return (
    <section className="header" data-flag={displayFlag.toLowerCase()}>
      <div className="line">
        {statusText} | {eventText} | {sessionText} | TTE {timeToGo} | Mode {viewModeLabel} |{' '}
        <strong>{displayFlag}</strong> | {ageText} | Favs {favCount}
      </div>
      <div className="line dim">
        Keys: h help | d demo | {searchLabel || 'Search: -'} {demoLabel}
        {errorText ? ` | Error: ${errorText}` : ''}
      </div>

      {(searchInputActive || searchQuery.length > MIN_VALUE) && (
        <div className="search-strip" role="search" aria-label="Search">
          <span className="search-label">Search:</span>
          <input
            aria-label="Search query"
            className="search-input"
            placeholder="Type to search..."
            readOnly={!searchInputActive}
            type="text"
            value={searchQuery}
          />
          {searchCount}
          {searchInputActive && <span className="search-cursor">_</span>}
        </div>
      )}
    </section>
  );
};

// web/src/lib/components/HeaderBar.svelte
<script lang="ts">
  // Compact status header matching TUI metadata order and flag-driven theming.

  import type { Series, SeriesSnapshot } from '$lib/types';

  export let series: Series;
  export let snapshot: SeriesSnapshot | null;
  export let viewModeLabel = 'Overall';
  export let favCount = 0;
  export let searchLabel = '';
  export let demoLabel = '';
  export let errorText = '';
  export let displayFlag = '-';

  $: ageText = snapshot?.last_update_unix_ms
    ? `Upd ${Math.max(0, Math.floor((Date.now() - snapshot.last_update_unix_ms) / 1000))}s`
    : 'Upd -';
  function displayEventName(raw: string): string {
    if (!raw || raw.trim() === '') {
      return '-';
    }
    return raw.trim();
  }

  function displaySessionName(activeSeries: Series, raw: string): string {
    if (!raw || raw.trim() === '') {
      return '-';
    }
    if (activeSeries === 'imsa') {
      const cleaned = normalizeImsaLabel(raw);
      return cleaned || raw;
    }
    return raw;
  }

  function normalizeImsaLabel(raw: string): string {
    const lower = raw.toLowerCase();
    let cleaned = raw.trim();
    if (lower.includes('weathertech')) {
      const idx = Math.max(raw.lastIndexOf('-'), raw.lastIndexOf('–'), raw.lastIndexOf('—'));
      if (idx >= 0) {
        cleaned = raw.slice(idx + 1).trim();
      }
    }
    return cleaned;
  }

  $: eventText = displayEventName(snapshot?.header.event_name || '-');
  $: sessionText = displaySessionName(series, snapshot?.header.session_name || '-');
  $: sessionDisplay = sessionText;
</script>

<section class="header" data-flag={displayFlag.toLowerCase()}>
  <div class="line">
    {snapshot?.status || 'Starting live timing...'} | {eventText} | {sessionDisplay} | TTE {snapshot?.header.time_to_go || '-'} | Mode {viewModeLabel} | <strong>{displayFlag}</strong> | {ageText} | Favs {favCount}
  </div>
  <div class="line dim">Keys: h help | d demo | {searchLabel || 'Search: -'} {demoLabel}{errorText ? ` | Error: ${errorText}` : ''}</div>
</section>

<style>
  .header {
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 0.28rem 0.48rem;
    position: relative;
    background: #10243a;
    color: #e7eef7;
    --header-dim: #afc0d6;
    margin-bottom: 0;
    overflow: hidden;
  }

  .header[data-flag*='green'] {
    background: #11a13a;
    color: #08170c;
    --header-dim: #112515;
    border-color: #0e8b32;
  }

  .header[data-flag*='yellow'],
  .header[data-flag*='code 60'],
  .header[data-flag*='safety'] {
    background: #f5dd08;
    color: #131100;
    --header-dim: #2f2a00;
    border-color: #d6bf00;
  }

  .header[data-flag*='red'] {
    background: #8e1e2b;
    color: #ffe6ea;
    --header-dim: #ffd0d7;
    border-color: #741522;
  }

  .header[data-flag*='white'] {
    background: #f2f5f9;
    color: #111821;
    --header-dim: #2f3f53;
    border-color: #cfd9e4;
  }

  .header[data-flag*='checkered'],
  .header[data-flag*='chequered'] {
    background: #dadfe8;
    color: #101722;
    --header-dim: #33465f;
    border-color: #bcc7d6;
  }

  .line {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    font-size: 0.75rem;
    line-height: 1.25;
  }

  .dim {
    color: var(--header-dim);
    margin-top: 0.08rem;
  }
</style>
