// web/src/lib/components/MessagesModal.svelte
<script lang="ts">
  // Race messages/notices modal - shows timing notices from the snapshot.
  import type { TimingNotice } from '$lib/types';
  import { tick, afterUpdate } from 'svelte';

  export let open = false;
  export let notices: TimingNotice[] = [];

  let selectedIdx = 0;
  let scrollContainer: HTMLDivElement | null = null;
  let modalEl: HTMLDialogElement | null = null;
  let previouslyFocused: Element | null = null;
  let wasOpen = false;

  function scrollToSelected() {
    if (scrollContainer && notices.length > 0) {
      const selectedElement = scrollContainer.children[selectedIdx] as HTMLElement;
      if (selectedElement) {
        selectedElement.scrollIntoView({ block: 'nearest' });
      }
    }
  }

  export function moveSelection(delta: number) {
    if (notices.length === 0) return;
    selectedIdx = (selectedIdx + delta + notices.length) % notices.length;
    scrollToSelected();
  }

  export function handleKey(event: KeyboardEvent): boolean {
    if (!open) return false;
    switch (event.key) {
      case 'ArrowUp':
      case 'k':
        moveSelection(-1);
        return true;
      case 'ArrowDown':
      case 'j':
        moveSelection(1);
        return true;
      case 'Home':
        selectedIdx = 0;
        scrollToSelected();
        return true;
      case 'End':
        selectedIdx = notices.length > 0 ? notices.length - 1 : 0;
        scrollToSelected();
        return true;
      case 'Escape':
        closeModal();
        return true;
    }
    return false;
  }

  export function getSelectedNotice(): TimingNotice | null {
    return notices[selectedIdx] ?? null;
  }

  export function resetSelection() {
    selectedIdx = 0;
  }

  afterUpdate(() => {
    if (!open) {
      wasOpen = false;
      return;
    }

    if (!wasOpen) {
      wasOpen = true;
      // Store the trigger element when opening
      previouslyFocused = document.activeElement;
      // Focus the first item
      const firstItem = modalEl?.querySelector('.entry') as HTMLElement | null;
      if (firstItem) {
        firstItem.focus();
      }
    }
  });

  function closeModal() {
    open = false;
    tick().then(() => {
      if (previouslyFocused && 'focus' in previouslyFocused) {
        (previouslyFocused as HTMLElement).focus();
      }
    });
  }

  function onBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      closeModal();
    }
  }
</script>

{#if open}
  <div
    class="backdrop"
    role="presentation"
    on:click={onBackdropClick}
  >
    <dialog
      bind:this={modalEl}
      class="modal"
      aria-labelledby="messages-title"
      on:click|stopPropagation
    >
      <h2 id="messages-title">Race Messages</h2>
      <div class="entries" bind:this={scrollContainer}>
        {#if notices.length === 0}
          <p class="empty">No active race messages.</p>
        {:else}
          {#each notices as notice, idx (notice.id)}
            <div
              class="entry"
              class:selected={idx === selectedIdx}
              role="button"
              tabindex="0"
            >
              <span class="marker">{idx === selectedIdx ? '>' : ' '}</span>
              <span class="time">{notice.time.trim() || '--:--:--'}</span>
              <span class="text">{notice.text.trim()}</span>
            </div>
          {/each}
        {/if}
      </div>
      <div class="footer">↑/↓ select | Esc or m close</div>
    </dialog>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgb(0 0 0 / 45%);
    display: grid;
    place-items: center;
    z-index: 220;
  }

  .modal {
    background: #0d1b2c;
    border: 1px solid var(--border);
    border-radius: 8px;
    width: min(50rem, 90vw);
    max-height: 80vh;
    padding: 0.75rem;
    display: flex;
    flex-direction: column;
  }

  h2 {
    margin: 0 0 0.45rem 0;
    font-size: 1rem;
  }

  .entries {
    flex: 1;
    overflow-y: auto;
    max-height: 60vh;
  }

  .empty {
    color: var(--text-dim);
    text-align: center;
    padding: 1rem;
  }

  .entry {
    display: flex;
    gap: 0.5rem;
    padding: 0.25rem 0;
    font-family: monospace;
  }

  .entry.selected {
    color: #f5dd08;
    font-weight: bold;
  }

  .marker {
    flex-shrink: 0;
    width: 1rem;
  }

  .time {
    flex-shrink: 0;
    width: 8ch;
    color: var(--text-dim);
  }

  .text {
    flex: 1;
    white-space: pre-wrap;
    word-wrap: break-word;
  }

  .footer {
    color: var(--text-dim);
    font-size: 0.75rem;
    margin-top: 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid var(--border);
  }
</style>

// web/src/lib/components/messages-modal.tsx
// Messages-modal.tsx - Race messages modal
import { useEffect, useRef, useCallback, useState, type JSX } from 'react';

import type { TimingNotice } from '../generated/web-shared';

interface MessagesModalProps {
  notices: TimingNotice[];
  onClose: () => void;
  open: boolean;
}

const ZERO = 0;
const ONE = 1;
const NEGATIVE_ONE = -1;
const INITIAL_INDEX = 0;
const TIMEOUT_DELAY = 0;
const NO_NOTICES = 0;

export const MessagesModal = function MessagesModal(props: MessagesModalProps): JSX.Element | null {
  const { notices, onClose, open } = props;
  const [selectedIdx, setSelectedIdx] = useState(INITIAL_INDEX);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const modalElRef = useRef<HTMLDialogElement>(null);
  const previouslyFocusedRef = useRef<Element | null>(null);
  const wasOpenRef = useRef(false);

  const scrollToSelected = useCallback((): void => {
    if (scrollContainerRef.current && notices.length > NO_NOTICES) {
      const element = scrollContainerRef.current.children[selectedIdx];
      if (element instanceof HTMLElement) {
        element.scrollIntoView({ block: 'nearest' });
      }
    }
  }, [selectedIdx, notices.length]);

  const moveSelection = useCallback(
    (delta: number): void => {
      if (notices.length === NO_NOTICES) {
        return;
      }
      setSelectedIdx((prev) => {
        const newIdx = (prev + delta + notices.length) % notices.length;
        return newIdx;
      });
    },
    [notices.length],
  );

  const closeModal = useCallback((): void => {
    onClose();
    // Restore focus after modal closes
    setTimeout((): void => {
      if (previouslyFocusedRef.current && 'focus' in previouslyFocusedRef.current) {
        const prevElement = previouslyFocusedRef.current;
        if (prevElement instanceof HTMLElement) {
          prevElement.focus();
        }
      }
    }, TIMEOUT_DELAY);
  }, [onClose]);

  const handleKeyDown = useCallback(
    (event: KeyboardEvent): void => {
      if (!open) {
        return;
      }

      switch (event.key) {
        case 'ArrowUp':
        case 'k': {
          event.preventDefault();
          moveSelection(NEGATIVE_ONE);
          break;
        }
        case 'ArrowDown':
        case 'j': {
          event.preventDefault();
          moveSelection(ONE);
          break;
        }
        case 'Home': {
          event.preventDefault();
          setSelectedIdx(ZERO);
          break;
        }
        case 'End': {
          event.preventDefault();
          setSelectedIdx(notices.length > NO_NOTICES ? notices.length - ONE : ZERO);
          break;
        }
        case 'Escape': {
          closeModal();
          break;
        }
        default: {
          // No action for other keys
          break;
        }
      }
    },
    [open, moveSelection, notices.length, closeModal],
  );

  useEffect((): (() => void) => {
    document.addEventListener('keydown', handleKeyDown);
    return (): void => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [handleKeyDown]);

  useEffect((): void => {
    if (!open) {
      wasOpenRef.current = false;
      return;
    }

    if (!wasOpenRef.current) {
      wasOpenRef.current = true;
      // Store the trigger element when opening
      previouslyFocusedRef.current = document.activeElement;
      // Focus the first item
      setTimeout((): void => {
        const firstItem = modalElRef.current?.querySelector('.entry');
        if (firstItem instanceof HTMLElement) {
          firstItem.focus();
        }
      }, TIMEOUT_DELAY);
    }
  }, [open]);

  // Scroll to selected when selectedIdx changes
  useEffect((): void => {
    if (open) {
      scrollToSelected();
    }
  }, [selectedIdx, open, scrollToSelected]);

  const onBackdropClick = useCallback(
    (event: React.MouseEvent<HTMLDivElement>): void => {
      if (event.target === event.currentTarget) {
        closeModal();
      }
    },
    [closeModal],
  );

  const stopPropagation = useCallback((event: React.MouseEvent): void => {
    event.stopPropagation();
  }, []);

  if (!open) {
    return null;
  }

  return (
    <div className="backdrop" role="presentation" onClick={onBackdropClick}>
      <dialog
        ref={modalElRef}
        className="modal messages-modal"
        aria-labelledby="messages-title"
        onClick={stopPropagation}
      >
        <h2 id="messages-title">Race Messages</h2>
        <div className="entries" ref={scrollContainerRef}>
          {notices.length === NO_NOTICES ? (
            <p className="empty">No active race messages.</p>
          ) : (
            notices.map((notice, idx) => (
              <div
                key={notice.id}
                className={`entry ${idx === selectedIdx ? 'selected' : ''}`}
                role="button"
                tabIndex={ZERO}
              >
                <span className="marker">{idx === selectedIdx ? '>' : ' '}</span>
                <span className="time">{notice.time.trim() || '--:--:--'}</span>
                <span className="text">{notice.text.trim()}</span>
              </div>
            ))
          )}
        </div>
        <div className="footer">↑/↓ select | Esc or m close</div>
      </dialog>
    </div>
  );
};
