// web/src/lib/components/series-modal.tsx
// Series-modal.tsx - Series picker modal
import { useEffect, useRef, useCallback, type JSX } from 'react';

import type { Series } from '../generated/web-shared';

interface SeriesModalProps {
  open: boolean;
  selectedSeries: Series;
  onPick: (series: Series) => void;
  onClose: () => void;
}

const SERIES_LIST: Series[] = ['imsa', 'nls', 'f1', 'wec', 'dhlm'];
const FOCUS_DELAY_MS = 0;

const handleDialogClick = (event: React.MouseEvent<HTMLDialogElement>): void => {
  event.stopPropagation();
};

export const SeriesModal = function SeriesModal(props: SeriesModalProps): JSX.Element | null {
  const { open, selectedSeries, onPick, onClose } = props;
  const modalElRef = useRef<HTMLDialogElement | null>(null);
  const previouslyFocusedRef = useRef<Element | null>(null);
  const wasOpenRef = useRef(false);

  const restoreFocus = useCallback((): void => {
    const previouslyFocused = previouslyFocusedRef.current;
    if (previouslyFocused instanceof HTMLElement) {
      previouslyFocused.focus();
    }
  }, []);

  const handleKeyDown = useCallback(
    (event: KeyboardEvent): void => {
      if (!open) {
        return;
      }

      if (event.key === 'Escape') {
        event.preventDefault();
        onClose();
        // Restore focus after closing
        setTimeout(restoreFocus, FOCUS_DELAY_MS);
      }
    },
    [open, onClose, restoreFocus],
  );

  useEffect(() => {
    if (!open) {
      wasOpenRef.current = false;
      return function noop(): void {
        // Intentionally empty
      };
    }
    document.addEventListener('keydown', handleKeyDown);
    return (): void => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [open, handleKeyDown]);

  useEffect(() => {
    if (open && !wasOpenRef.current) {
      wasOpenRef.current = true;
      // Store the trigger element when opening
      previouslyFocusedRef.current = document.activeElement;
      // Focus the selected button when modal opens
      const selectedEl = modalElRef.current?.querySelector('button.selected');
      if (selectedEl instanceof HTMLButtonElement) {
        selectedEl.focus();
      }
    }
  }, [open]);

  const handleBackdropClick = (): void => {
    onClose();
    // Restore focus after closing
    setTimeout(restoreFocus, FOCUS_DELAY_MS);
  };

  const handlePick = (series: Series): void => {
    onPick(series);
    // Restore focus after picking
    setTimeout(restoreFocus, FOCUS_DELAY_MS);
  };

  if (!open) {
    return null;
  }

  return (
    <div
      className="backdrop"
      role="presentation"
      onClick={handleBackdropClick}
      onKeyDown={(event): void => {
        if (event.key === 'Enter') {
          handleBackdropClick();
        }
      }}
      tabIndex={-1}
    >
      <dialog
        ref={modalElRef}
        className="modal series-modal"
        aria-labelledby="series-title"
        onClick={handleDialogClick}
      >
        <h2 id="series-title">Select Series</h2>
        <div className="list">
          {SERIES_LIST.map((series) => (
            <button
              key={series}
              type="button"
              className={series === selectedSeries ? 'selected' : ''}
              onClick={(): void => {
                handlePick(series);
              }}
            >
              {series.toUpperCase()}
            </button>
          ))}
        </div>
      </dialog>
    </div>
  );
};

// web/src/lib/components/SeriesModal.svelte
<script lang="ts">
  // Series chooser popup used by keyboard shortcut `t` and click fallback.
  import type { Series } from '$lib/types';
  import { tick, afterUpdate } from 'svelte';

  export let open = false;
  export let selectedSeries: Series = 'imsa';
  export let onPick: (series: Series) => void = () => {};

  const seriesList: Series[] = ['imsa', 'nls', 'f1', 'wec', 'dhlm'];
  let modalEl: HTMLElement | null = null;
  let previouslyFocused: Element | null = null;
  let wasOpen = false;

  afterUpdate(() => {
    if (!open) {
      wasOpen = false;
      return;
    }

    if (!wasOpen) {
      wasOpen = true;
      // Store the trigger element when opening
      previouslyFocused = document.activeElement;
      // Focus the selected button
      const selected = modalEl?.querySelector('button.selected') as HTMLButtonElement | null;
      if (selected) {
        selected.focus();
      }
    }
  });

  function handleKeydown(event: KeyboardEvent) {
    if (!open) return;

    if (event.key === 'Escape') {
      open = false;
      event.preventDefault();
      // Restore focus
      tick().then(() => {
        if (previouslyFocused && 'focus' in previouslyFocused) {
          (previouslyFocused as HTMLElement).focus();
        }
      });
    }
  }

  function handlePick(series: Series) {
    onPick?.(series);
    tick().then(() => {
      if (previouslyFocused && 'focus' in previouslyFocused) {
        (previouslyFocused as HTMLElement).focus();
      }
    });
  }

  function closeModal() {
    open = false;
    tick().then(() => {
      if (previouslyFocused && 'focus' in previouslyFocused) {
        (previouslyFocused as HTMLElement).focus();
      }
    });
  }
</script>

<svelte:window on:keydown={handleKeydown} />

  {#if open}
  <div
    class="backdrop"
    role="presentation"
    on:click={closeModal}
    on:keydown={(e) => e.key === 'Enter' && closeModal()}
    tabindex="-1"
  >
    <dialog
      bind:this={modalEl}
      class="modal"
      aria-labelledby="series-title"
      on:click|stopPropagation
    >
      <h2 id="series-title">Select Series</h2>
      <div class="list">
        {#each seriesList as series (series)}
          <button
            type="button"
            class:selected={series === selectedSeries}
            on:click={() => handlePick(series)}
          >
            {series.toUpperCase()}
          </button>
        {/each}
      </div>
    </dialog>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgb(0 0 0 / 45%);
    display: grid;
    place-items: center;
    z-index: 220;
  }

  .modal {
    background: #0d1b2c;
    border: 1px solid var(--border);
    border-radius: 8px;
    width: min(22rem, 90vw);
    max-height: 72vh;
    padding: 0.75rem;
    display: flex;
    flex-direction: column;
  }

  h2 {
    margin: 0 0 0.55rem 0;
    font-size: 1rem;
  }

  .list {
    display: grid;
    gap: 0.5rem;
    overflow: auto;
  }

  button {
    background: #13263a;
    border: 1px solid #334965;
    color: var(--text);
    padding: 0.5rem;
    border-radius: 8px;
    cursor: pointer;
  }

  button.selected {
    border-color: var(--accent);
    background: #1b3c62;
    font-weight: 700;
  }
</style>
